influxdb:
  protocol: http
  address: influxdb2
  port: 80
  org: influxdata
  bucket: default
  token: 

speedtest:
  server: # leave both id and name blank for auto.  if both id and name are defined, id is used
    id:    # 5 digit ID of the server to use. 
    name:  # fqdn of the server to use. 

logging:
  level: info # Valid Options: panic, fatal, error, warn, info, debug, trace