{
 "title": "Internet Speedtest Data",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Current Download",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"download\" and r._field == \"bandwidth\")\n    |> group(columns: [\"bandwidth\"])\n    |> last()"
    }
   ]
  },
  {
   "title": "Current Upload",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"upload\" and r._field == \"bandwidth\")\n    |> group(columns: [\"bandwidth\"])\n    |> last()"
    }
   ]
  },
  {
   "title": "Current Latency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"latency\")\n    |> group(columns: [\"latency\"])\n    |> last()"
    }
   ]
  },
  {
   "title": "Raw",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"result\" and r._field == \"id\")\n    |> group(columns: [\"id\"])\n    |> last()"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"download\" and r._field == \"bandwidth\")\n    |> group(columns: [\"bandwidth\"])\n    "
    },
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"upload\" and r._field == \"bandwidth\")\n    |> group(columns: [\"bandwidth\"])\n"
    }
   ]
  },
  {
   "title": "Ping",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"latency\")\n    |> group(columns: [\"latency\"])\n    "
    },
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"ping\" and r._field == \"jitter\")\n    |> group(columns: [\"jitter\"])"
    }
   ]
  },
  {
   "title": "Packet Loss",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"speedtestd\")\n    |> range(start: v.timeRangeStart)\n    |> filter(fn: (r) => r._measurement == \"packet\" and r._field == \"loss\")\n    |> group(columns: [\"loss\"])\n    "
    }
   ]
  }
 ]
}