apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "speedtestd.fullname" . }}-cron
  labels:
    {{- include "speedtestd.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "speedtestd.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            volumeMounts:
            - name: "{{ template "speedtestd.fullname" . }}-config"
              mountPath: "/etc/speedtestd.yaml"
              subPath: "speedtestd.yaml"
              readOnly: true
            security_context:
              capabilities:
                drop: [ all ]
              allow_privilege_escalation: false
              run_as_non_root: true
              read_only_root_filesystem: true
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 10 }}
            {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          volumes:
            - name: {{ template "speedtestd.fullname" . }}-config
              secret:
                secretName: {{ template "speedtestd.fullname" . }}-config
                optional: false
          restartPolicy: OnFailure