apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ template "speedtestd.fullname" . }}-cron
  labels:
    {{- include "speedtestd.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  startingDeadlineSeconds: {{ .Values.cron.startingDeadlineSeconds }}
  concurrencyPolicy: {{ .Values.cron.concurrencyPolicy }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "speedtestd.serviceAccountName" . }}
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            # ports:
            #   - name: http
            #     containerPort: 80
            #     protocol: TCP
            # livenessProbe:
            #   httpGet:
            #     path: /
            #     port: http
            # readinessProbe:
            #   httpGet:
            #     path: /
            #     port: http
            volumeMounts:
            - name: "{{ template "speedtestd.fullname" . }}-config"
              mountPath: "/etc/speedtestd.yaml"
              subPath: "speedtestd.yaml"
            env:
            - name: INFLUXDB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbCredentials.existingSecret | default (include "speedtestd.fullname" .) }}
                  key: {{ .Values.dbCredentials.userKey | default "username" }}
            - name: INFLUXDB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.dbCredentials.existingSecret | default (include "speedtestd.fullname" .) }}
                  key: {{ .Values.dbCredentials.passwordKey | default "password" }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          volumes:
            - name: {{ template "speedtestd.fullname" . }}-config
              configMap:
                name: {{ template "speedtestd.fullname" . }}-config
          restartPolicy: OnFailure