{{- if not .Values.dbCredentials.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "speedtestd.fullname" . }}
  labels:
    {{- include "speedtestd.labels" . | nindent 4 }}
{{- with .Values.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
type: Opaque
data:
  username: {{ .Values.dbCredentials.username | b64enc | quote }}
  password: {{ .Values.dbCredentials.password | b64enc | quote }}
{{- end }}